export const PAKISTAN_CITIES = [
  'Karachi',
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Gujranwala',
  'Peshawar',
  'Multan',
  'Hyderabad',
  'Islamabad',
  'Quetta',
  'Bahawalpur',
  'Sargodha',
  'Sialkot',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Rahim Yar Khan',
  'Jhang',
  'Dera Ghazi Khan',
  'Gujrat',
  'Sahiwal',
  'Wah Cantt',
  'Mardan',
  'Kasur',
  'Okara',
  'Mingora',
  'Nawabshah',
  'Chiniot',
  'Kamoke',
  'Hafizabad',
  'Sadiqabad',
  'Mirpur Khas',
  'Burewala',
  'Kohat',
  'Muzaffargarh',
  'Khanewal',
  'Turbat',
  'Muzaffarabad',
  'Abbottabad',
  'Mandi Bahauddin',
  'Dera Ismail Khan',
  'Jacobabad',
  'Shikarpur',
  'Jhelum',
  'Khanpur',
  'Khairpur',
  'Khuzdar',
  'Pakpattan',
  'Hub',
  'Gojra',
  'Muridke',
  'Bahawalnagar',
  'Samundri',
  'Tando Allahyar',
  'Tando Adam',
  'Jaranwala',
  'Chishtian',
  'Attock',
  'Vehari',
  'Kot Abdul Malik',
  'Ferozewala',
  'Gwadar',
  'Gilgit',
  'Skardu',
  'Mirpur (AJK)',
].sort();
